name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test-h5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v6
        with:
          node-version: 20.19.5
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - name: Run build:h5
        run: pnpm build:h5

  test-mp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v6
        with:
          node-version: 20.19.5
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - name: Run build:mp
        run: pnpm build:mp
